### ISSUE TITLE
clippy-preview and rls-preview missing on various nightly toolchains

### ISSUE THREAD

**Issue by behnam** [rust-lang/rustup#1532]
After a fresh `rustup` installation, I see adding component does work for `stable` and `beta`, but not for `nightly`.

On `stable`:
```shell
$ rustup component list --toolchain stable | grep clippy
clippy-preview-x86_64-apple-darwin (installed)
$ rustup component add clippy-preview --toolchain stable
info: downloading component 'clippy-preview'
info: installing component 'clippy-preview'
```

On `beta`:
```shell
$ rustup component list --toolchain beta | grep clippy
clippy-preview-x86_64-apple-darwin
$ rustup component add clippy-preview --toolchain beta
info: downloading component 'clippy-preview'
info: installing component 'clippy-preview'
```

On `nightly`:
```shell
$ rustup component list --toolchain nightly | grep clippy
$ rustup component add clippy-preview --toolchain nightly
error: component 'clippy-preview' for 'x86_64-apple-darwin' is unavailable for download
```

**Comment by behnam** [comment]
Looks like `rls-preview` is a similar situation.

**Comment by robertohuertasm** [comment]
I think this a generic issue not only related to Mac. My CI is complaining for Linux and Windows too. 😞

**Comment by BlinkyStitt** [comment]
I agree that this is larger than OSX. 
```
error: component 'clippy-preview' for 'x86_64-unknown-linux-gnu' is unavailable for download
```

**Comment by BlinkyStitt** [comment]
This is a useful site for checking the status of the components https://mexus.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html

**Comment by behnam** [comment]
This has been fixed since 2018-11-06, so let's just close the issue. (Please feel free to re-open if it needs investigation.)

![screen shot 2018-11-11 at 11 38 46 pm](https://user-images.githubusercontent.com/37169/48333085-ffc59380-e60a-11e8-962f-2f2472520af0.png)

**Comment by macisamuele** [comment]
Hey @behnam on clippy is still missing on [x86_64-apple-darwin](https://mexus.github.io/rustup-components-history/x86_64-apple-darwin.html).
I don't know if still makes sense to comment here.
