### ISSUE TITLE
"missing installed component" error should be translated through renames

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rustup#2440]
As [documented](https://forge.rust-lang.org/infra/channel-layout.html#content-of-channel-manifests), component names passed to `rustup component add` are translated through the `renames` table, and component names in `rustup component list` are translated backwards through `renames`. However, when rustup skips a nightly version because it doesn't have an installed component, the error message gives the "preview" component name, and doesn't translate backwards through `renames`:

```text
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2020-07-25, rust version 1.47.0-nightly (5ef299eb9 2020-07-24)
info: skipping nightly which is missing installed component 'rustfmt-preview'
info: syncing channel updates for 'nightly-2020-07-24-x86_64-unknown-linux-gnu'
info: latest update on 2020-07-24, rust version 1.47.0-nightly (0820e54a8 2020-07-23)
info: skipping nightly which is missing installed component 'rustfmt-preview'
```

`rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`
`rustup show`:
```text
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/josh/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
system

installed targets for active toolchain
--------------------------------------

wasm32-wasi
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.45.0 (5c1f21c3b 2020-07-13)

```

**Comment by kinnison** [comment]
Well spotted.  This should definitely be fixed otherwise users may get confused.

**Comment by kinnison** [comment]
This ought to be fairly straightforward to correct.  I'd be happy to discuss it either here or on Discord with anyone interested in attempting a fix.

**Comment by rbtcollins** [comment]
We should probably fix the stringification stuff for these types so that it is fixed systematically.

**Comment by kinnison** [comment]
> We should probably fix the stringification stuff for these types so that it is fixed systematically.

IIRC the component doesn't have back-references to its manifest which is needed for renaming.

**Comment by salpalvv** [comment]
> Well spotted. This should definitely be fixed otherwise users may get confused.

I am confused, how do I update nightly when it's skipping? 

```
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
info: skipping nightly which is missing installed component 'rustfmt-preview'
info: syncing channel updates for 'nightly-2020-08-11-x86_64-pc-windows-msvc'
512.0 KiB / 512.0 KiB (100 %) 366.5 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-11, rust version 1.47.0-nightly (770bd3d1d 2020-08-10)
info: skipping nightly which is missing installed component 'rustfmt-preview'
info: syncing channel updates for 'nightly-2020-08-10-x86_64-pc-windows-msvc'
503.7 KiB / 503.7 KiB (100 %) 368.0 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-10, rust version 1.47.0-nightly (18f3be770 2020-08-09)
info: skipping nightly which is missing installed component 'rustfmt-preview'
```

Edit: I just uninstalled nightly and tried to reinstall and I'm still getting the skipping per #2417's suggestion. Now I am locked out of being able to do any work as I need nightly features but can't install nightly. 

Edit2: typed `rustfmt` just to see and it...downloaded latest nightly so, it looks like it's working again. I am no longer blocked but, confused and slightly annoyed. 

```
PS E:\rust\nina> rustup install nightly-2020-08-12
info: syncing channel updates for 'nightly-2020-08-12-x86_64-pc-windows-msvc'
512.0 KiB / 512.0 KiB (100 %) 367.1 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
error: component 'rustfmt' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel nightly-2020-08-12
Sometimes not all components are available in any given nightly.
PS E:\rust\nina> rustfmt
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
warning: Force-skipping unavailable component 'rustfmt-x86_64-pc-windows-msvc'
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
```

**Comment by kinnison** [comment]
@salpalvv this isn't really the issue to discuss this, but you're missing the point that the attempt to use rustfmt ended up failing to use it, though that's a bit confusing too it's not relevant to this issue.  As such I'm going to hide your comment and mine so that the issue isn't confused by this.  If you're still struggling, opening a fresh issue describing your situation, what you're trying to do and what confusing things is going on will be your best bet.  Thanks.

**Comment by salpalvv** [comment]
How is this offtopic? I'm literally getting the failure described in the OP. I am just looking for a workaround when I run into this issue or, at least an explanation of what is happening. If I must, I will make a new issue when this happens again but I don't see how ignoring my issue is helpful when I am just asking a question relevant to the open issue.

**Comment by rbtcollins** [comment]
This bug describes how the message that is output should be translated to deal with the metadata in the publication process that deal with publishing it on the web.

Your question/error is something to do with the installation process, and entirely unrelated to this bug, other than that the same message which is being discussed is output in both cases. 

Please follow the request and open a new ticket, it was made in good faith.
