### ISSUE TITLE
MacOS, RustUp installation doesn't work as expected.

### ISSUE THREAD

**Issue by AntiMoron** [rust-lang/rustup#3658]
### Problem

As POST TITLE, I think you can reproduce it too.

### Steps

1. visit https://www.rust-lang.org/tools/install
2. copy the command as recommanded: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
3. Choose `1) Proceed with installation (default)`
4. Wait for the progress finish.
5. The final step, Boom.

![image](https://github.com/rust-lang/rustup/assets/6587734/e5ff59f1-dca1-4589-9d8b-439f1706c6d0)

### Rustup version

```console
I don't know, I think it's latest, as I `curl`ed and `pipe`ed `sh`.
```

### Installed toolchains

```console
xx
```

**Comment by AntiMoron** [comment]
I've known the reason, and rustup should fix this compatibility issue. I've configured my `~/.curlrc` file.

```
cat ~/.curlrc

-w "\n\ndnslookup: %{time_namelookup} | connect: %{time_connect} | appconnect: %{time_appconnect} | pretransfer: %{time_pretransfer} | starttransfer: %{time_starttransfer} | total: %{time_total} | size: %{size_download}\n"
```

So, the debug info of this curl call triggered this bug.

**Comment by rami3l** [comment]
@AntiMoron Thanks for filing this issue!

Does the problem persist when using `https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh` instead of https://sh.rustup.rs?
